### ISSUE TITLE
Reading the screen of the 2955 via GPIB

### ISSUE THREAD

**Issue by m1geo** [daturach/Documentation#1]
I enjoyed the drawing on the 2955 screen article.

https://github.com/daturach/Documentation/wiki/GPIB-interface-(Marconi-2955)

I wonder if you know how I can read the screen, for example, to create a screen capture. Is there a way to read the pixel data and generate a bitmap?

Thanks
George M1GEO

**Comment by daturach** [comment]
Hello George
Thanks
I wouldn't know if it's possible. You can try to ask on the Marconi-Test-Instruments forum. 
By the way, someone created a board to replace the Marconi display. Maybe there is something to investigate there.

**Comment by m1geo** [comment]
Thanks! I hear also there is a GPIB plotter/printer function, so may be able to parse the data for that into a script on the PC.

PS, I got the code in your example to work ([more here](https://twitter.com/m1geo/status/1541893695649488898)):
![image](https://user-images.githubusercontent.com/758615/182273808-92099fa9-cc9a-4ba1-b612-a3dd524ce881.png)
